<a href="https://colab.research.google.com/github/lejejefr/ECM_2526_FinalProject/blob/main/Scripts/DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install PyGithub

Collecting PyGithub
  Downloading pygithub-2.8.1-py3-none-any.whl.metadata (3.9 kB)
Collecting pynacl>=1.4.0 (from PyGithub)
  Downloading pynacl-1.6.2-cp38-abi3-manylinux_2_34_x86_64.whl.metadata (10.0 kB)
Requirement already satisfied: requests>=2.14.0 in /usr/local/lib/python3.12/dist-packages (from PyGithub) (2.32.4)
Requirement already satisfied: pyjwt>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.4.0->PyGithub) (2.11.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from PyGithub) (4.15.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from PyGithub) (2.5.0)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.4.0->PyGithub) (43.0.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pynacl>=1.4.0->PyGithub) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.14.0->PyGithub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.14.0->PyGithub) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.14.0->PyGithub) (2026.2.25)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->pynacl>=1.4.0->PyGithub) (3.0)
Downloading pygithub-2.8.1-py3-none-any.whl (432 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 432.7/432.7 kB 10.5 MB/s eta 0:00:00
Downloading pynacl-1.6.2-cp38-abi3-manylinux_2_34_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 21.5 MB/s eta 0:00:00
Installing collected packages: pynacl, PyGithub
Successfully installed PyGithub-2.8.1 pynacl-1.6.2

In [2]:
#ce script sert à nettoyer les données pour notre training set
from github import Github
import pandas as pd
url = 'https://raw.githubusercontent.com/lejejefr/ECM_2526_FinalProject/refs/heads/main/Data/RawData.csv'
df = pd.read_csv(url)
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,28910,JJ442189,10/06/2025 05:19:00 PM,016XX W 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,False,False,...,17.0,71.0,01A,1166608.0,1852321.0,2025,10/14/2025 03:58:46 PM,41.750334,-87.665045,"(41.75033427, -87.665045312)"
1,28909,JJ442109,10/06/2025 05:15:00 PM,000XX N KILBOURN AVE,110,HOMICIDE,FIRST DEGREE MURDER,GAS STATION,False,False,...,28.0,26.0,01A,1146387.0,1899777.0,2025,10/14/2025 03:58:46 PM,41.880968,-87.737940,"(41.88096768, -87.737940272)"
2,28908,JJ441599,10/06/2025 09:17:00 AM,056XX W WASHINGTON BLVD,110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,True,...,29.0,25.0,01A,1138415.0,1900175.0,2025,10/14/2025 03:58:46 PM,41.882208,-87.767204,"(41.88220788, -87.767203679)"
3,28907,JJ441303,10/06/2025 03:36:00 AM,026XX W 39TH PL,110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,12.0,58.0,01A,1159522.0,1878370.0,2025,10/14/2025 03:58:46 PM,41.821964,-87.690298,"(41.821964415, -87.690297894)"
4,28906,JJ439875,10/04/2025 08:35:00 PM,038XX W ROOSEVELT RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,False,False,...,24.0,29.0,01A,1151170.0,1894442.0,2025,10/12/2025 03:43:35 PM,41.866235,-87.720517,"(41.866235446, -87.720517147)"

In [3]:
#je suis en train de taffer sur le projet homicide (je veux qu'on l'appelle comme ça à partir de maintenant.),
#je suis en train de poursuivre le nettoyage des données. pour l'instant j'ai créé un nouveau data frame qu'on
#utilisera pour entrainer le modèle avec ID, heure, jour de la semaine, jour de l'année, latitude et longitude.
#j'ai mis heure jour semaine et jour mois pour voir si y a de la saisonnalité (genre plus de crime la nuit, le
#week end, l'hiver). On a pas besoin de la colonne primary type parce qu'on a gardé que les homicides, et les
#autres colonnes je vois pas à quoi elles servent. si ça vous semble correct ba let's go

dates = pd.to_datetime(df['Date'])

df['time'] = dates.dt.hour * 3600 + dates.dt.minute * 60 + dates.dt.second
df['day of week'] = dates.dt.day_of_week
df['day of year'] = dates.dt.day_of_year

df.head()

/tmp/ipykernel_694/3597225523.py:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dates = pd.to_datetime(df['Date'])

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,time,day of week,day of year
0,28910,JJ442189,10/06/2025 05:19:00 PM,016XX W 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,False,False,...,1166608.0,1852321.0,2025,10/14/2025 03:58:46 PM,41.750334,-87.665045,"(41.75033427, -87.665045312)",62340,0,279
1,28909,JJ442109,10/06/2025 05:15:00 PM,000XX N KILBOURN AVE,110,HOMICIDE,FIRST DEGREE MURDER,GAS STATION,False,False,...,1146387.0,1899777.0,2025,10/14/2025 03:58:46 PM,41.880968,-87.737940,"(41.88096768, -87.737940272)",62100,0,279
2,28908,JJ441599,10/06/2025 09:17:00 AM,056XX W WASHINGTON BLVD,110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,True,...,1138415.0,1900175.0,2025,10/14/2025 03:58:46 PM,41.882208,-87.767204,"(41.88220788, -87.767203679)",33420,0,279
3,28907,JJ441303,10/06/2025 03:36:00 AM,026XX W 39TH PL,110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,1159522.0,1878370.0,2025,10/14/2025 03:58:46 PM,41.821964,-87.690298,"(41.821964415, -87.690297894)",12960,0,279
4,28906,JJ439875,10/04/2025 08:35:00 PM,038XX W ROOSEVELT RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,False,False,...,1151170.0,1894442.0,2025,10/12/2025 03:43:35 PM,41.866235,-87.720517,"(41.866235446, -87.720517147)",74100,5,277

In [9]:
df = df[["ID","Latitude","Longitude","time","day of week","day of year"]]
df = df[df["Longitude"] > -90]

In [10]:
df.describe()

,ID,Latitude,Longitude,time,day of week,day of year
count,1.393700e+04,13937.000000,13937.000000,13937.000000,13937.000000,13937.000000
mean,8.289846e+04,41.817290,-87.668187,44381.437827,3.230179,190.464734
std,8.603390e+05,0.078640,0.057413,27944.143584,2.061337,97.012704
min,6.340000e+02,41.644818,-87.904123,0.000000,0.000000,1.000000
25%,4.159000e+03,41.757257,-87.714760,15780.000000,1.000000,115.000000
50%,2.178100e+04,41.803585,-87.665192,48600.000000,3.000000,192.000000
75%,2.541300e+04,41.880778,-87.624568,69960.000000,5.000000,268.000000
max,1.373461e+07,42.022548,-87.525759,86340.000000,6.000000,366.000000

In [8]:


g = Github()
repo = g.get_user().get_repo("ECM_2526_FinalProject")


csv_content = df.to_csv(index=False)


repo.create_file(
    path="Data/CleanData.csv",
    message="Add cleaned data",
    content=csv_content,
    branch="main"
)

GithubException: Requires authentication: 401 {"message": "Requires authentication", "documentation_url": "https://docs.github.com/rest", "status": "401"}